version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sweepro-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sweepro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sweepro-network

  redis:
    image: redis:latest
    container_name: sweepro-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sweepro-network

volumes:
  postgres_data:
  redis_data:

networks:
  sweepro-network:
    driver: bridge 